# MongoDB Configuration
nameOverride: ""
fullnameOverride: ""

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 27017
  targetPort: 27017

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

labels:
  app: mongo

podLabels: {}

annotations: {}
