apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.name" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  ports:
  - name: kafka
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}