keda:
  enabled: true
  deployment:
    name: customer-facing-server
    namespace: default
  scaling:
    pollingInterval: 10
    cooldownPeriod: 30
    minReplicas: 1
    maxReplicas: 5
  prometheus:
    serverAddress: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090
    metricName: nginx_ingress_controller_requests
    threshold: "2"
    query: 'sum(rate(nginx_ingress_controller_requests{path="/getAllUserBuys"}[5m]))'

serviceMonitor:
  enabled: true
  labels:
    app: ingress-nginx
    release: kube-prometheus-stack
  namespace: ingress-nginx
  interval: 15s
  path: /metrics
  port: metrics
  scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
